### ISSUE TITLE
Bug get_dimension_stereotypes

### ISSUE THREAD

**Issue by SimonGuillot** [SINr-Embeddings/sinr#81]
![image](https://github.com/SINr-Embeddings/sinr/assets/47661058/2debd0aa-57fb-438f-96c1-df228653c607)

La fonction get_dimension_stereotypes a un soucis de matching entre les indices des dimensions dans le dictionnaire du modèle et les indices dans dimensions dans les vecteurs. 
Par exemple, pour la dimension indicée "2" dans le dictionnaire, on voit qu'elle est à la 7e position dans la liste.

Possiblement cela est du au filtrage du modèle ? 

Les dimensions enlevées par le filtrage prenant la valeur -1 avec la numérotation continuant pour les dimensions conservées. 
Cependant, la fonction get_dimensions_stereotypes a l'air de fonctionner avec les indices de la liste, et renvoie donc souvent les indices de la dimensions -1.

![image](https://github.com/SINr-Embeddings/sinr/assets/47661058/63cb8339-64d2-44a9-bfb1-1823caebb1c5)

**Comment by nicolasdugue** [comment]
Merci @SimonGuillot pour ce retour !
Je pense que ça n'a pas d'impact sur les méthodes comme get_obj_stereotypes, mais que ça impacte en effet get_dimension_stereotypes que l'on utilisait pas guère jusque là.
En tout cas, le dernier imprim'écran est assez parlant. 
Le fix du bug est prioritaire @aberanger et ça peut etre bien d'ajouter un cas de test spécifique sur cette fonctionnalité. On ne l'a probablement pas testée :(
